### ISSUE TITLE
Rename repo to just `tl`

### ISSUE THREAD

**Issue by Wmbat** [build2-packaging/tl#3]
@boris-kolpackov 

I transfered ownership of this project to build2-packaging without renaming it first. The packaging of `tl::expected` and `tl::optional` is almost complete. The only main problem left would be the actual name of the repo. 

Would it be possible to rename `build-tl` to simply `tl` (as it is the namespace used by all the packages within the repo) ?

**Comment by boris-kolpackov** [comment]
Done, sorry took me while.
